repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: ^\.vscode/
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: ["--install-types", "--non-interactive", "--ignore-missing-imports"]
  - repo: https://github.com/whtsky/pre-commit-pretty-format-json5
    rev: "1.0.0"
    hooks:
    - id: pretty-format-json5

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.8
    hooks:
      - id: uv-lock
