name: Release
on:
  push:
    tags:
      - '*'


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        uv venv
        uv sync
    - name: Set OS name
      run: echo "OS_NAME=$(echo ${{ matrix.os }} | sed -e 's/ubuntu-latest/x86_64-linux/' -e 's/windows-latest/x86_64-windows.zip/' -e 's/macos-13/x86_64-darwin/' -e 's/macos-latest/aarch64-darwin.tar.gz/')" >> $GITHUB_ENV
    - name: build release
      run: |
        uv run pyinstaller --noconfirm Mutenix.spec -- --os-suffix $OS_NAME
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
