name: Release
on:
  push:
    tags:
      - '*'


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        uv venv
        uv sync
    - name: build release
      run: |
        uv run pyinstaller --noconfirm Mutenix.spec
      
    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.3
      env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
